TIPO_FORMACION = (
    ('COMPLEMENTARIA', 'COMPLEMENTARIA'),
    ('A LA MEDIDA', 'A LA MEDIDA'),
)

TIEMPO_CONTRATO = (
    ('MENOS DE 6 MESES', 'MENOS DE 6 MESES'),
    ('MAS DE 6 MESES', 'MAS DE 6 MESES')
)

ESTADO_FORMACION = (
    ('DESERTO', 'DESERTO'),
    ('SE GRADUO', 'SE GRADUO'),
    ('RETIRADO', 'RETIRADO'),
    ('CONTRATADO', 'CONTRATADO')
)