# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencialaboralpersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_a', to='personas.Persona'),
        ),
        migrations.AlterField(
            model_name='formacioncomplementariapersona',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_b', to='personas.Persona'),
        ),
    ]
