# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 20:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='casa',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='manzana', chained_model_field='numero_manzana', on_delete=django.db.models.deletion.CASCADE, to='personas.Casa'),
        ),
    ]
