# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='numero_telefono_3',
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero_telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='numero_telefono_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
